---

- name: "Check if subscription should be enabled"
  include_tasks: install.yml
  when: redhat_subscription_enabled

- name: "Check if subscription should be disabled"
  include_tasks: uninstall.yml
  when: not redhat_subscription_enabled
