---
- name: Register and auto-subscribe to available content.
  redhat_subscription:
    state: present
    username: "{{ redhat_username }}"
    password: "{{ redhat_password }}"
    autosubscribe: true